let tests={},current=null,answers=[],index=0,score=0,timer=null,seconds=0;
const $=s=>document.querySelector(s),$$=s=>[...document.querySelectorAll(s)];
const esc=v=>String(v??"").replace(/[&<>"']/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#039;"}[c]));
const fmt=s=>`${Math.floor(s/60).toString().padStart(2,"0")}:${(s%60).toString().padStart(2,"0")}`;
async function init(){tests=await(await fetch("data/practice-tests.json")).json();$$("[data-test]").forEach(b=>b.onclick=()=>start(b.dataset.test));$("#fullMock").onclick=fullMock;$("#writingBtn").onclick=writing;$("#speakingBtn").onclick=speaking;$("#scoreCalc").onclick=calculator}
function start(k){current=tests[k];answers=[];index=0;score=0;seconds=3600;$("#testModal").classList.add("show");render();timer=setInterval(()=>{seconds--;let c=$("#clock");if(c)c.textContent=fmt(seconds);if(seconds<=0){clearInterval(timer);finish()}},1000)}
function render(){let q=current.questions[index];$("#testBody").innerHTML=`<div class="modal-head"><div><span class="badge">QUESTION ${index+1}/${current.questions.length}</span><h2>${esc(current.title)}</h2></div><div class="clock" id="clock">${fmt(seconds)}</div></div><div class="passage">${esc(q.source)}</div><div class="question"><h3>${esc(q.q)}</h3><div class="options">${q.options.map((o,i)=>`<button class="option" data-a="${i}">${String.fromCharCode(65+i)}. ${esc(o)}</button>`).join("")}</div></div><div class="test-nav"><button class="secondary" id="quit">Quit</button><button class="primary" id="next">${index===current.questions.length-1?"Finish":"Next →"}</button></div>`;$$("[data-a]").forEach(b=>b.onclick=()=>{answers[index]=+b.dataset.a;$$("[data-a]").forEach(x=>x.classList.toggle("selected",x===b))});$("#next").onclick=()=>{index++;index<current.questions.length?render():finish()};$("#quit").onclick=()=>{clearInterval(timer);$("#testModal").classList.remove("show")}}
function band(r,type){if(type==="gt"){if(r>=35)return"7";if(r>=30)return"6";if(r>=23)return"5";return"4 or below"}if(r>=39)return"9";if(r>=37)return"8.5";if(r>=35)return"8";if(r>=33)return"7.5";if(r>=30)return"7";if(r>=27)return"6.5";if(r>=23)return"6";if(r>=19)return"5.5";if(r>=15)return"5";if(r>=13)return"4.5";return"4 or below"}
function finish(){clearInterval(timer);score=current.questions.reduce((a,q,i)=>a+(answers[i]===q.answer?1:0),0);let b=band(score,current.title.includes("General")?"gt":"acad");localStorage.setItem("buye_last_test",JSON.stringify({title:current.title,score,total:40,band:b}));$("#testBody").innerHTML=`<div class="result"><div class="result-ring">${b}</div><h2>${esc(current.title)} complete</h2><p><b>${score}/40</b> correct</p><p class="note">Practice estimate only. Review your mistakes before repeating the test.</p><button class="primary" id="review">Review answers</button><button class="secondary" id="close">Back</button></div>`;$("#review").onclick=review;$("#close").onclick=()=>$("#testModal").classList.remove("show")}
function review(){let h=`<div class="modal-head"><h2>Answer review</h2><button class="icon-btn" id="x">×</button></div>`;current.questions.forEach((q,i)=>{let ok=answers[i]===q.answer;h+=`<div class="review-item"><b>${i+1}. ${esc(q.q)}</b><span class="${ok?"ok":"bad"}">${ok?"Correct":"Review"}</span><p>Your answer: ${answers[i]==null?"Not answered":esc(q.options[answers[i]])}</p><p>Correct: <b>${esc(q.options[q.answer])}</b></p></div>`});$("#testBody").innerHTML=h;$("#x").onclick=()=>$("#testModal").classList.remove("show")}
function fullMock(){let html=`<div class="modal-head"><h2>Full Mock Test</h2><button class="icon-btn" id="x">×</button></div><p class="note">A complete 40-question objective mock is available for each skill. Choose a section below.</p><div class="full-grid">${Object.entries(tests).map(([k,v])=>`<button class="test-choice" data-full="${k}"><b>${esc(v.title)}</b><span>40 questions • timed</span></button>`).join("")}</div><p class="note">Writing and Speaking are assessed separately because they require human/examiner judgement.</p>`;$("#testBody").innerHTML=html;$("#x").onclick=()=>$("#testModal").classList.remove("show");$$("[data-full]").forEach(b=>b.onclick=()=>{start(b.dataset.full)})}
function writing(){fetch("data/writing-speaking.json").then(r=>r.json()).then(d=>{let w=d.writing;$("#writingModal").classList.add("show");$("#writingBody").innerHTML=`<div class="modal-head"><h2>${w.title}</h2><button class="icon-btn" onclick="$('#writingModal').classList.remove('show')">×</button></div>${w.tasks.map(t=>`<section class="task"><h3>${t.task} <small>${t.time} minutes • ${t.min}+ words</small></h3><p>${esc(t.prompt)}</p><textarea placeholder="Write your response here…"></textarea><div class="rubric">${w.rubric.map(r=>`<label><span>${esc(r)}</span><select><option>Choose</option><option>Developing</option><option>Competent</option><option>Strong</option><option>Very strong</option></select></label>`).join("")}</div></section>`).join("")}<p class="note">Task 2 carries more weight than Task 1 in IELTS Writing. This page is a self-review tool, not an official scoring service.</p>`})}
function speaking(){fetch("data/writing-speaking.json").then(r=>r.json()).then(d=>{let s=d.speaking;$("#speakingModal").classList.add("show");$("#speakingBody").innerHTML=`<div class="modal-head"><h2>Speaking Simulation</h2><button class="icon-btn" onclick="$('#speakingModal').classList.remove('show')">×</button></div>${s.parts.map(p=>`<section class="task"><h3>${esc(p[0])}</h3><p>${esc(p[1])}</p>${p[2].map(q=>`<div class="prompt"><b>${esc(q)}</b><div class="rubric">${["Fluency and coherence","Lexical resource","Grammatical range and accuracy","Pronunciation"].map(r=>`<label><span>${r}</span><select><option>Choose</option><option>Developing</option><option>Competent</option><option>Strong</option><option>Very strong</option></select></label>`).join("")}</div></div>`).join("")}</section>`).join("")}<p class="note">Official Speaking is 11–14 minutes and has three parts. Use a phone/computer recorder to practise your delivery.</p>`})}
function calculator(){let html=`<div class="modal-head"><h2>Overall Band Calculator</h2><button class="icon-btn" onclick="$('#calcModal').classList.remove('show')">×</button></div><p class="note">Enter four section bands. The overall score is the average rounded to the nearest half band.</p><div class="calc-grid">${["Listening","Reading","Writing","Speaking"].map(x=>`<label>${x}<input class="band-input" type="number" min="1" max="9" step=".5" placeholder="e.g. 6.5"></label>`).join("")}</div><button class="primary" id="calc">Calculate</button><div id="calcResult"></div>`;$("#calcModal").classList.add("show");$("#calcBody").innerHTML=html;$("#calc").onclick=()=>{let a=$$(".band-input").map(x=>Number(x.value));if(a.some(x=>x<1||x>9)){alert("Enter four bands from 1 to 9.");return}let avg=a.reduce((x,y)=>x+y,0)/4;let r=Math.round(avg*2)/2;$("#calcResult").innerHTML=`<div class="calc-result"><b>${r.toFixed(1)}</b><span>Overall practice band</span><small>Average: ${avg.toFixed(2)}</small></div>`}}
init();